// This file was generated by counterfeiter
package v2fakes

import (
	"sync"

	"code.cloudfoundry.org/cli/actor/v2action"
	"code.cloudfoundry.org/cli/command/v2"
)

type FakeCreateUserActor struct {
	CreateUserStub        func(username string, password string) (v2action.Warnings, error)
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		username string
		password string
	}
	createUserReturns struct {
		result1 v2action.Warnings
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCreateUserActor) CreateUser(username string, password string) (v2action.Warnings, error) {
	fake.createUserMutex.Lock()
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		username string
		password string
	}{username, password})
	fake.recordInvocation("CreateUser", []interface{}{username, password})
	fake.createUserMutex.Unlock()
	if fake.CreateUserStub != nil {
		return fake.CreateUserStub(username, password)
	} else {
		return fake.createUserReturns.result1, fake.createUserReturns.result2
	}
}

func (fake *FakeCreateUserActor) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *FakeCreateUserActor) CreateUserArgsForCall(i int) (string, string) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return fake.createUserArgsForCall[i].username, fake.createUserArgsForCall[i].password
}

func (fake *FakeCreateUserActor) CreateUserReturns(result1 v2action.Warnings, result2 error) {
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 v2action.Warnings
		result2 error
	}{result1, result2}
}

func (fake *FakeCreateUserActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCreateUserActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v2.CreateUserActor = new(FakeCreateUserActor)
